// =====================================================
// TypeForge — Structured Course Definitions
// =====================================================

import { CourseDefinition } from '@/types';

export const COURSES: CourseDefinition[] = [
    {
        id: 'touch-typing-basics',
        title: 'Touch Typing Basics',
        description: 'Learn proper finger placement from home row to the full keyboard.',
        icon: '🏠',
        lessons: [
            {
                id: 'home-row-fj',
                title: 'Home Row: F & J',
                description: 'Start with the two index finger keys — the foundation of touch typing.',
                targetKeys: ['f', 'j'],
                minWpm: 10,
                minAccuracy: 90,
                starThresholds: [15, 25, 40],
            },
            {
                id: 'home-row-dk',
                title: 'Home Row: D & K',
                description: 'Add the middle fingers to your repertoire.',
                targetKeys: ['f', 'j', 'd', 'k'],
                minWpm: 10,
                minAccuracy: 90,
                starThresholds: [15, 25, 40],
            },
            {
                id: 'home-row-sl',
                title: 'Home Row: S & L',
                description: 'Ring fingers join the party.',
                targetKeys: ['f', 'j', 'd', 'k', 's', 'l'],
                minWpm: 12,
                minAccuracy: 90,
                starThresholds: [18, 28, 42],
            },
            {
                id: 'home-row-a-semi',
                title: 'Home Row: A & ;',
                description: 'Complete the home row with your pinkies.',
                targetKeys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';'],
                minWpm: 12,
                minAccuracy: 88,
                starThresholds: [18, 28, 42],
            },
            {
                id: 'home-row-gh',
                title: 'Home Row: G & H',
                description: 'Master the center keys reached by your index fingers.',
                targetKeys: ['f', 'j', 'd', 'k', 's', 'l', 'a', ';', 'g', 'h'],
                minWpm: 15,
                minAccuracy: 88,
                starThresholds: [20, 30, 45],
            },
            {
                id: 'home-row-review',
                title: 'Home Row Review',
                description: 'Practice the entire home row until it feels natural.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';'],
                minWpm: 18,
                minAccuracy: 92,
                starThresholds: [25, 35, 50],
            },
            {
                id: 'top-row-ru',
                title: 'Top Row: R & U',
                description: 'Index fingers reach up to the top row.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'r', 'u'],
                minWpm: 15,
                minAccuracy: 85,
                starThresholds: [20, 30, 45],
            },
            {
                id: 'top-row-ei',
                title: 'Top Row: E & I',
                description: 'Middle fingers reach for the top row.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'r', 'u', 'e', 'i'],
                minWpm: 15,
                minAccuracy: 85,
                starThresholds: [20, 30, 45],
            },
            {
                id: 'top-row-wo',
                title: 'Top Row: W & O',
                description: 'Ring fingers stretch to the top.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'r', 'u', 'e', 'i', 'w', 'o'],
                minWpm: 15,
                minAccuracy: 85,
                starThresholds: [20, 30, 45],
            },
            {
                id: 'top-row-ty',
                title: 'Top Row: T & Y',
                description: 'Index finger extensions to T and Y.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'r', 'u', 'e', 'i', 'w', 'o', 't', 'y'],
                minWpm: 15,
                minAccuracy: 85,
                starThresholds: [22, 32, 48],
            },
            {
                id: 'top-row-qp',
                title: 'Top Row: Q & P',
                description: 'Pinkies reach for the corners.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'r', 'u', 'e', 'i', 'w', 'o', 't', 'y', 'q', 'p'],
                minWpm: 15,
                minAccuracy: 82,
                starThresholds: [22, 32, 48],
            },
            {
                id: 'top-row-review',
                title: 'Top Row Review',
                description: 'Practice home + top row together.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
                minWpm: 18,
                minAccuracy: 88,
                starThresholds: [25, 35, 50],
            },
            {
                id: 'bottom-row-vm',
                title: 'Bottom Row: V & M',
                description: 'Index fingers drop to the bottom row.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'v', 'm'],
                minWpm: 15,
                minAccuracy: 85,
                starThresholds: [20, 30, 45],
            },
            {
                id: 'bottom-row-c-comma',
                title: 'Bottom Row: C & ,',
                description: 'Middle fingers descend.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'v', 'm', 'c', ','],
                minWpm: 15,
                minAccuracy: 85,
                starThresholds: [20, 30, 45],
            },
            {
                id: 'bottom-row-x-period',
                title: 'Bottom Row: X & .',
                description: 'Ring fingers reach down.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'v', 'm', 'c', ',', 'x', '.'],
                minWpm: 15,
                minAccuracy: 85,
                starThresholds: [20, 30, 45],
            },
            {
                id: 'bottom-row-z-slash',
                title: 'Bottom Row: Z & /',
                description: 'Pinkies take the bottom corners.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'v', 'm', 'c', ',', 'x', '.', 'z', '/'],
                minWpm: 15,
                minAccuracy: 82,
                starThresholds: [20, 30, 45],
            },
            {
                id: 'bottom-row-bn',
                title: 'Bottom Row: B & N',
                description: 'Index finger extensions for B and N.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'v', 'm', 'c', ',', 'x', '.', 'z', '/', 'b', 'n'],
                minWpm: 15,
                minAccuracy: 82,
                starThresholds: [20, 30, 45],
            },
            {
                id: 'bottom-row-review',
                title: 'Bottom Row Review',
                description: 'Practice all three rows together.',
                targetKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/'],
                minWpm: 18,
                minAccuracy: 85,
                starThresholds: [25, 35, 50],
            },
            {
                id: 'full-keyboard-practice',
                title: 'Full Keyboard Practice',
                description: 'Use every letter key with proper finger placement.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 20,
                minAccuracy: 88,
                starThresholds: [28, 40, 55],
            },
            {
                id: 'full-keyboard-mastery',
                title: 'Full Keyboard Mastery',
                description: 'The final challenge — type fluently with all keys.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 25,
                minAccuracy: 92,
                starThresholds: [35, 50, 65],
            },
        ],
    },
    {
        id: 'speed-building',
        title: 'Speed Building',
        description: 'Increase your typing speed with common words and patterns.',
        icon: '⚡',
        lessons: [
            {
                id: 'common-words-easy',
                title: 'Common Words: Easy',
                description: 'Type the 50 most common English words.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 25,
                minAccuracy: 90,
                starThresholds: [30, 45, 60],
            },
            {
                id: 'common-words-medium',
                title: 'Common Words: Medium',
                description: 'Slightly longer common words.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 30,
                minAccuracy: 90,
                starThresholds: [35, 50, 65],
            },
            {
                id: 'common-bigrams',
                title: 'Common Bigrams',
                description: 'Practice the most frequent two-letter combinations (th, he, in, er...).',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 30,
                minAccuracy: 88,
                starThresholds: [35, 50, 70],
            },
            {
                id: 'common-trigrams',
                title: 'Common Trigrams',
                description: 'Practice three-letter combos (the, and, ing, ion...).',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 30,
                minAccuracy: 88,
                starThresholds: [35, 50, 70],
            },
            {
                id: 'speed-burst-30',
                title: 'Speed Burst: 30 WPM',
                description: 'Push for 30 WPM with simple words.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 30,
                minAccuracy: 88,
                starThresholds: [35, 45, 60],
            },
            {
                id: 'speed-burst-40',
                title: 'Speed Burst: 40 WPM',
                description: 'Push for 40 WPM.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 40,
                minAccuracy: 88,
                starThresholds: [45, 55, 70],
            },
            {
                id: 'speed-burst-50',
                title: 'Speed Burst: 50 WPM',
                description: 'Push for 50 WPM.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 50,
                minAccuracy: 85,
                starThresholds: [55, 65, 80],
            },
            {
                id: 'speed-burst-60',
                title: 'Speed Burst: 60 WPM',
                description: 'Break 60 WPM!',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 60,
                minAccuracy: 85,
                starThresholds: [65, 75, 90],
            },
            {
                id: 'speed-burst-70',
                title: 'Speed Burst: 70 WPM',
                description: 'Push toward 70 WPM.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 70,
                minAccuracy: 85,
                starThresholds: [75, 85, 100],
            },
            {
                id: 'speed-burst-80',
                title: 'Speed Burst: 80 WPM',
                description: 'Pro-level speed: 80 WPM.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 80,
                minAccuracy: 85,
                starThresholds: [85, 95, 110],
            },
            {
                id: 'alternating-hands',
                title: 'Alternating Hands',
                description: 'Words that alternate between left and right hand keys.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 35,
                minAccuracy: 90,
                starThresholds: [40, 55, 70],
            },
            {
                id: 'same-hand-words',
                title: 'Same Hand Words',
                description: 'Challenge: words typed mostly with one hand.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 25,
                minAccuracy: 88,
                starThresholds: [30, 40, 55],
            },
            {
                id: 'long-words',
                title: 'Long Words',
                description: 'Practice with longer, more complex words.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 25,
                minAccuracy: 85,
                starThresholds: [30, 40, 55],
            },
            {
                id: 'speed-endurance',
                title: 'Speed Endurance',
                description: 'Maintain high speed over a longer passage.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 40,
                minAccuracy: 90,
                starThresholds: [45, 55, 70],
            },
            {
                id: 'speed-mastery',
                title: 'Speed Mastery',
                description: 'The ultimate speed challenge.',
                targetKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
                minWpm: 50,
                minAccuracy: 90,
                starThresholds: [60, 75, 90],
            },
        ],
    },
    {
        id: 'punctuation-mastery',
        title: 'Punctuation Mastery',
        description: 'Master periods, commas, quotes, and special characters.',
        icon: '✏️',
        lessons: [
            {
                id: 'period-comma',
                title: 'Period & Comma',
                description: 'The most common punctuation marks.',
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), '.', ','],
                minWpm: 20,
                minAccuracy: 88,
                starThresholds: [25, 35, 50],
            },
            {
                id: 'question-exclamation',
                title: 'Question & Exclamation',
                description: 'Express yourself with ? and !',
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), '.', ',', '?', '!'],
                minWpm: 18,
                minAccuracy: 85,
                starThresholds: [22, 32, 45],
            },
            {
                id: 'apostrophe-quotes',
                title: 'Apostrophe & Quotes',
                description: "Contractions and quotations.",
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), "'", '"'],
                minWpm: 18,
                minAccuracy: 85,
                starThresholds: [22, 32, 45],
            },
            {
                id: 'colon-semicolon',
                title: 'Colon & Semicolon',
                description: 'Precise punctuation for complex sentences.',
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), ':', ';'],
                minWpm: 18,
                minAccuracy: 85,
                starThresholds: [22, 32, 45],
            },
            {
                id: 'parentheses',
                title: 'Parentheses & Brackets',
                description: 'Grouping punctuation: ( ) [ ] { }',
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), '(', ')', '[', ']', '{', '}'],
                minWpm: 15,
                minAccuracy: 82,
                starThresholds: [20, 28, 40],
            },
            {
                id: 'dash-underscore',
                title: 'Dash & Underscore',
                description: 'The hyphen and underscore keys.',
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), '-', '_'],
                minWpm: 18,
                minAccuracy: 85,
                starThresholds: [22, 32, 45],
            },
            {
                id: 'slash-backslash',
                title: 'Slash & Backslash',
                description: 'Forward and backward: / \\',
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), '/', '\\'],
                minWpm: 18,
                minAccuracy: 85,
                starThresholds: [22, 32, 45],
            },
            {
                id: 'at-hash-dollar',
                title: 'At, Hash & Dollar',
                description: 'Common programming symbols: @ # $',
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), '@', '#', '$'],
                minWpm: 15,
                minAccuracy: 82,
                starThresholds: [20, 28, 40],
            },
            {
                id: 'mixed-punctuation',
                title: 'Mixed Punctuation',
                description: 'All common punctuation mixed together.',
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), '.', ',', '!', '?', "'", '"', ':', ';', '-'],
                minWpm: 20,
                minAccuracy: 85,
                starThresholds: [25, 35, 50],
            },
            {
                id: 'punctuation-mastery-final',
                title: 'Punctuation Mastery',
                description: 'The ultimate punctuation challenge.',
                targetKeys: [...'abcdefghijklmnopqrstuvwxyz'.split(''), '.', ',', '!', '?', "'", '"', ':', ';', '-', '(', ')', '@', '#'],
                minWpm: 22,
                minAccuracy: 88,
                starThresholds: [28, 38, 52],
            },
        ],
    },
];

/**
 * Find a course by ID.
 */
export function getCourse(courseId: string): CourseDefinition | undefined {
    return COURSES.find((c) => c.id === courseId);
}

/**
 * Find a lesson within a course.
 */
export function getLesson(courseId: string, lessonId: string) {
    const course = getCourse(courseId);
    if (!course) return undefined;
    return course.lessons.find((l) => l.id === lessonId);
}
